apiVersion: apps/v1
kind: Deployment
metadata:
  name: zero-trust-app
  labels:
    app.kubernetes.io/name: zero-trust-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: zero-trust-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: zero-trust-app
    spec:
      serviceAccountName: zero-trust-app
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: application
          image: zero-trust-app:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          securityContext:
            runAsNonRoot: true
            privileged: false
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 128Mi
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
