apiVersion: apps/v1
kind: Deployment
metadata:
  name: deliberately-insecure-example
  namespace: zero-trust-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deliberately-insecure-example
  template:
    metadata:
      labels:
        app: deliberately-insecure-example
    spec:
      containers:
        - name: insecure
          image: nginx:latest
          securityContext:
            allowPrivilegeEscalation: true
