apiVersion: apps/v1
kind: Deployment
metadata:
  name: zero-trust-app-insecure-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zero-trust-app-insecure-demo
  template:
    metadata:
      labels:
        app: zero-trust-app-insecure-demo
    spec:
      containers:
        - name: application
          image: zero-trust-app:latest
          securityContext:
            allowPrivilegeEscalation: true
            readOnlyRootFilesystem: false
